### PR TITLE
FAPagat

### PR DESCRIPTION
**Pull request by Juke34**
I replaced GAAS scripts by those from AGAT. 
Not tested, must be tested before to be merged.

### CODE REVIEW

**Comment by LucileSol** [comment]
I ran 
```
nextflow run -c params.config -profile nbis,conda /home/lucso605/git/NBIS/pipelines/nextflow/AugustusTraining/AugustusTraining.nf
```
I am on the FAPagat branch  
and I got the following error : 
```
Oops .. something went wrong
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'split_maker_evidence (codingGeneFeatures)'

Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /home/lucso605/test/test_nextflow/AugustusTraining/work/conda/augustus-training-4bc0830038011717c3af0e27c2f0dc31 --file /home/lucso605/git/NBIS/pipelines/nextflow/AugustusTraining/environment.yml
  status : 1
  message:
    ResolvePackageNotFound: 
      - agat=1.0.0
```

in my  params.config is : 
```
params.maker_evidence_gff = "/projects/test/test_nextflow/AugustusTraining/data/codingGeneFeatures.gff"
params.genome = "/projects/test/test_nextflow/AugustusTraining/data/genome.fa"
//params.outdir = "results"

//params.gff_gene_model_filter_options = '-c -r -d 500 -a 0.3'

//params.codon_table = 1

//params.test_size = 100
//params.flank_region_size = 500
```

**Comment by Juke34** [comment]
Should be fine now, I mixed up it is version 0.1.0 version 1.0.0 does not exist yet

**Comment by LucileSol** [comment]
New error same command line 

```
[73/69b65e] process > split_maker_evidence (codingGeneFeatures) [100%] 1 of 1, failed: 1 ✘
[-        ] process > model_selection_by_AED                    -
[-        ] process > retain_longest_isoform                    -
[-        ] process > remove_incomplete_gene_models             -
[-        ] process > filter_by_locus_distance                  -
[-        ] process > extract_protein_sequence                  -
[-        ] process > blast_makeblastdb                         -
[-        ] process > blast_recursive                           -
[-        ] process > gff_filter_by_blast                       -
[-        ] process > gff2gbk                                   -
[-        ] process > gbk2augustus                              -
Oops .. something went wrong
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'split_maker_evidence (codingGeneFeatures)'

Caused by:
  Process `split_maker_evidence (codingGeneFeatures)` terminated with an error exit status (1)

Command executed:

  agat_sp_split_by_level2_feature.pl -g codingGeneFeatures.gff -o maker_results_noAbinitio_clean

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  /var/lib/slurm-llnl/slurmd/job08515/slurm_script: line 275: activate: No such file or directory

Work dir:
  /home/lucso605/test/test_nextflow/AugustusTraining/work/73/69b65e9393b7decb972e2f0e1f46f4

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

**Comment by Juke34** [comment]
I tried locally this command works: ` agat_sp_split_by_level2_feature.pl -g codingGeneFeatures.gff -o maker_results_noAbinitio_clean`

**Comment by mahesh-panchal** [comment]
This is an issue with how conda is installed on our system.
At the moment I can fix this by doing:
```
source /sw/anaconda/2019.10/etc/profile.d/conda.sh
export PATH="$PATH:/home/sw/anaconda/2019.10/bin"
nextflow run -profile nbis,conda -c "$CONFIG" "$NF_SCRIPT"
```

**Comment by mahesh-panchal** [comment]
Testing the functional annotation preparation changes, interproscan is not found. 

Should I add it back in?

**Comment by Juke34** [comment]
Works fine for me

**Comment by mahesh-panchal** [comment]
If it's working fine for you, then that probably means you've got something we're missing.

**Comment by Juke34** [comment]
I used this env:  
`nextflow-env             /sw/anaconda/2019.10/envs/nextflow-env`

and here my command:
`nextflow run -profile nbis,conda /home/jacda119/git/NBIS/pipelines/nextflow/AugustusTraining/AugustusTraining.nf --genome 'genome.fa' --maker_evidence_gff 'maker_annotation.gff' --outdir 'augustus_training_result' --gff_gene_model_filter_options '-c -r -d 500 -a 0.3' --codon_table '1' --test_size '100' --flank_region_size '500' `

**Comment by mahesh-panchal** [comment]
Is interproscan in your own PATH? It's not by default for me. 

Also the interproscan installed in `/projects/references/interproscan/` has a library missing 'libdw.so.1'. This can be found in the conda blast environment, but not in the interproscan folder.

**Comment by Juke34** [comment]
Sorry confusion, I talk about the AugustusTraining pipeline haven't try interproscan. But this PR change only access to GAAS scripts that are now in AGAT. So this change sounds fine.

**Comment by mahesh-panchal** [comment]
You have changes to two pipelines here. The augutus training and the functional annotation preparation. Only the augustus training workflow works. The other is broken.

**Comment by Juke34** [comment]
Actually I'm wrong, I have removed that: 
`env.PATH='${PATH}:${HOME}/git/NBIS/GAAS/annotation/Tools/bin:/projects/interproscan/my_interproscan/interproscan-5.38-76.0/'`

That could be the problem

**Pull request merged**
